sudo: false
language: rust
cache:
  cargo: true
  directories:
    - "$SCCACHE_DIR"
    - "$HOME/.xargo"

addons:
  apt:
    packages:
    - libc6-i386
    - lib32stdc++6
    - lib32gcc1
    - patch

rust:
  - nightly

env:
  global:
    # sccache
    - CARGO_HOME="$HOME/.cargo"
    - RUSTC_WRAPPER="sccache"
    - SCCACHE_DIR="$HOME/.cache/sccache"
    # vitasdk
    - VITASDK="$HOME/.local/share/vitasdk"
    - PATH="$VITASDK/bin:$PATH"

install:
  - ci/travis/setup.sh

script:
  - cargo make build                                    # Compile natively
  - cargo make xbuild                                   # Cross-compile

before_deploy:
  - cd $TRAVIS_BUILD_DIR

deploy:
  provider: script
  script: cargo make publish-flow
  on:
    tags: true
    repo: vita-rust/vitallocator
    rust: nightly

notifications:
  email:
  - althonosdev@gmail.com
